### PR TITLE
Readme fixes for Preview 6

### PR DESCRIPTION
**Pull request by jongalloway**
This pull request includes changes to multiple files in the `labs` directory, primarily in the `README.md` files for labs 1, 2, and 5. The changes are mainly focused on improving the clarity of the instructions and correcting minor errors. 

Changes to lab instructions:

* [`labs/1-Create-Catalog-API/README.md`](diffhunk://#diff-30c696f9ae4465ab0f7e2b651fdb20d7cec17350460bc74b177830115fb416e4L9-R9): Modified references to solution files, clarified instructions, and corrected minor errors. [[1]](diffhunk://#diff-30c696f9ae4465ab0f7e2b651fdb20d7cec17350460bc74b177830115fb416e4L9-R9) [[2]](diffhunk://#diff-30c696f9ae4465ab0f7e2b651fdb20d7cec17350460bc74b177830115fb416e4L89-R89) [[3]](diffhunk://#diff-30c696f9ae4465ab0f7e2b651fdb20d7cec17350460bc74b177830115fb416e4L161-R166) [[4]](diffhunk://#diff-30c696f9ae4465ab0f7e2b651fdb20d7cec17350460bc74b177830115fb416e4R181-R183) [[5]](diffhunk://#diff-30c696f9ae4465ab0f7e2b651fdb20d7cec17350460bc74b177830115fb416e4L210-R211)
* [`labs/2-Create-Blazor-Frontend/README.md`](diffhunk://#diff-01eabd1ca47f45215c74e1d1af2efc1a302da65a34d43ed051ea71e5fc4158aeL9-R9): Updated instructions for opening files, creating new files, and modifying existing files. Also corrected minor errors in the instructions. [[1]](diffhunk://#diff-01eabd1ca47f45215c74e1d1af2efc1a302da65a34d43ed051ea71e5fc4158aeL9-R9) [[2]](diffhunk://#diff-01eabd1ca47f45215c74e1d1af2efc1a302da65a34d43ed051ea71e5fc4158aeL40-R40) [[3]](diffhunk://#diff-01eabd1ca47f45215c74e1d1af2efc1a302da65a34d43ed051ea71e5fc4158aeL143-R146) [[4]](diffhunk://#diff-01eabd1ca47f45215c74e1d1af2efc1a302da65a34d43ed051ea71e5fc4158aeR158) [[5]](diffhunk://#diff-01eabd1ca47f45215c74e1d1af2efc1a302da65a34d43ed051ea71e5fc4158aeL261-R289) [[6]](diffhunk://#diff-01eabd1ca47f45215c74e1d1af2efc1a302da65a34d43ed051ea71e5fc4158aeR317) [[7]](diffhunk://#diff-01eabd1ca47f45215c74e1d1af2efc1a302da65a34d43ed051ea71e5fc4158aeL327-L334) [[8]](diffhunk://#diff-01eabd1ca47f45215c74e1d1af2efc1a302da65a34d43ed051ea71e5fc4158aeL346-R366)
* [`labs/5-Add-Checkout/README.md`](diffhunk://#diff-e09cfa9583aca7e7b6f1b9f5414a52b60cf69a6720e33a628993f5e1d405af21L9-R9): Updated the solution file reference in the instructions.

These changes aim to improve the readability and accuracy of the lab instructions, making it easier for users to follow along and complete the labs.

### CODE REVIEW

**Review by DamianEdwards — APPROVED** [review]
💯

**Comment by DamianEdwards** [comment]
@jongalloway any reason this is still draft?

**Comment by jongalloway** [comment]
Still adding some stuff for other labs. Lab 3 updates incoming tonight.

**Comment by jongalloway** [comment]
I think the Lab 3 part needs more review so I'm going to send that in as a separate PR.

**Pull request merged**
